# -*- coding: utf-8 -*-
"""youtube_mp3_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yi717vBuJ2cYyWa5BvDx3VOYrg1ZEx8X
"""

pip install yt-dlp
pip install ffmpeg-python

from yt_dlp import YoutubeDL
import os

def download_youtube_mp3(url, output_path="."):
    """
    Function to download YouTube video as MP3 using yt-dlp

    Parameters:
        url (str): YouTube video URL
        output_path (str): Output directory path (default: current directory)

    Returns:
        str: Path to the saved MP3 file
    """
    try:
        # Create output directory if it doesn't exist
        os.makedirs(output_path, exist_ok=True)

        # Configure yt-dlp options
        ydl_opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }],
            'outtmpl': os.path.join(output_path, '%(title)s.%(ext)s'),
            'verbose': True
        }

        # Download and convert to MP3
        with YoutubeDL(ydl_opts) as ydl:
            print(f"Starting download from: {url}")
            info = ydl.extract_info(url, download=True)
            output_file = os.path.join(output_path, f"{info['title']}.mp3")
            print(f"Download complete: {output_file}")
            return output_file

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        return None

# Usage example
if __name__ == "__main__":
    # YouTube video URL
    video_url = "https://www.youtube.com/watch?v=Zbo7UY8dxh8"

    # Execute download
    output_file = download_youtube_mp3(video_url, "downloads")

    if output_file:
        print(f"File successfully saved to: {output_file}")
    else:
        print("Download failed")